PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;

DELETE FROM announcements;
DELETE FROM app_feature_flags;
DELETE FROM business_invites;
DELETE FROM business_trials;
DELETE FROM business_users;
DELETE FROM businesses;
DELETE FROM camera_events;
DELETE FROM camera_sources;
DELETE FROM checklist_items;
DELETE FROM checklist_sections;
DELETE FROM creator_category_registry;
DELETE FROM daily_specials;
DELETE FROM daily_specials_editors;
DELETE FROM documents;
DELETE FROM employee_profile_edit_requests;
DELETE FROM employee_profiles;
DELETE FROM employee_spotlight;
DELETE FROM iot_ingest_guard;
DELETE FROM list_items;
DELETE FROM list_sections;
DELETE FROM meeting_notes;
DELETE FROM recipes;
DELETE FROM schedule_shift_offers;
DELETE FROM schedule_shifts;
DELETE FROM schedule_week_team;
DELETE FROM schedule_weeks;
DELETE FROM schedule_preferences;
DELETE FROM schedule_role_definitions;
DELETE FROM schedule_departments;
DELETE FROM sensor_nodes;
DELETE FROM temps;
DELETE FROM todo_assignments;
DELETE FROM todo_completion_log;
DELETE FROM todos;
DELETE FROM trial_denials;
DELETE FROM user_invites;
DELETE FROM user_preferences;
DELETE FROM user_schedule_availability;
DELETE FROM user_schedule_departments;
DELETE FROM user_schedule_time_off_requests;
DELETE FROM whiteboard_posts;
DELETE FROM whiteboard_review;

COMMIT;
PRAGMA foreign_keys = ON;
