#pragma once

// Copy this file to crimini_iot_config.h. Do not commit real secrets.

// Radio: ESP-NOW uses 2.4 GHz Wi-Fi channels. The gateway Wi-Fi AP channel and
// the sensor channel must match. Keep TX power conservative unless lab testing
// and module certification support a higher value.
#define CRIMINI_ESPNOW_CHANNEL 6
#define CRIMINI_TX_POWER_QDBM 34  // 8.5 dBm; ESP-IDF units are quarter-dBm.
#define CRIMINI_SENSOR_INTERVAL_SECONDS 300
#define CRIMINI_SENSOR_BURST_COUNT 3
#define CRIMINI_SENSOR_BURST_SPACING_MS 160
#define CRIMINI_SENSOR_RANDOM_JITTER_SECONDS 20

// Gateway Wi-Fi + API.
#define CRIMINI_WIFI_SSID ""
#define CRIMINI_WIFI_PASSWORD ""
#define CRIMINI_API_BASE_URL "https://criminiops.com"
#define CRIMINI_GATEWAY_SERIAL "crimini-gateway-001"
#define CRIMINI_GATEWAY_DEVICE_KEY "sknns_iot_replace_from_factory_manifest"
#define CRIMINI_OPTIONAL_BUSINESS_ID ""
#define CRIMINI_GATEWAY_BATCH_MAX 24
#define CRIMINI_GATEWAY_FLUSH_MS 5000

// Paste the root CA used by your production API certificate. Leave blank only
// while building sensor-only firmware. The gateway refuses HTTPS posts without it.
#define CRIMINI_TLS_ROOT_CA_PEM ""
// #define CRIMINI_ALLOW_INSECURE_TLS_FOR_LAB 1

// Sensor node identity. Generated by tools/provision-manifest.mjs.
#define CRIMINI_NODE_SERIAL "crimini-sensor-001"
#define CRIMINI_NODE_SHARED_SECRET "replace_from_factory_manifest"

// Gateway MAC address printed by the gateway on boot. Program this into nodes.
#define CRIMINI_GATEWAY_MAC { 0x24, 0x6f, 0x28, 0x00, 0x00, 0x00 }

// Temperature input. DS18B20 is the default intended probe for cooler/freezer use.
#define CRIMINI_USE_DS18B20 1
#define CRIMINI_DS18B20_PIN 2

// Optional battery divider ADC. Leave disabled for USB-powered lab nodes.
// #define CRIMINI_BATTERY_ADC_PIN 3
// #define CRIMINI_BATTERY_DIVIDER_RATIO 2.0f

typedef struct {
  const char* serial;
  const char* secret;
} CriminiKnownNode;

static const CriminiKnownNode CRIMINI_KNOWN_NODES[] = {
  { "crimini-sensor-001", "replace_from_factory_manifest" }
};
